version: '3'
services:
  gerrit:
    image: "gerritcodereview/gerrit"
    ports:
     - "8080:8080"
     - "29418:29418"
    links:
     - dot
    volumes:
     - ${PWD}/volumes/git:/var/gerrit/git
     - ${PWD}/volumes/db:/var/gerrit/db
     - ${PWD}/volumes/index:/var/gerrit/index
     - ${PWD}/volumes/cache:/var/gerrit/cache
     - ${PWD}/volumes/plugins:/var/gerrit/plugins
#    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit
#    entrypoint: java -jar /var/gerrit/bin/gerrit.war reindex -d /var/gerrit
  dot:
    image: "omerio/graphviz-server"
    ports:
     - "8081:8080"
    entrypoint: java -jar /opt/graphviz-server/dist/DotGraphics.jar 8080
